include/infstr.h File Reference
Classes
struct infStr
struct for infinite string
Typedefs
typedef struct infStr infStr
Functions
infStr * initStr (infStr *str)
Initialize infStr.
int fillStr (infStr *str, char *chars, int num)
fill the string from the beginning.
infStr * append (infStr *str, char *chars, int num)
Append chars to the end of InfStr.
int clear (infStr *str)
Clear the string.
int allocStr (infStr *str, int num)
allocating memory
void deallocStr (infStr *str)
deallocating memory should be called before lifetme of infStr end
Typedef Documentation
infStr
typedef struct infStr infStr
Definition at line 15 of file infstr.h.
Function Documentation
allocStr()
int allocStr (infStr * str, int num)
allocating memory
Returns
Number of character that has been allocated
Parameters
str infStr obj
Definition at line 130 of file infStr.c.
                                   {
  str->str = (char*) malloc(sizeof(char)*num);
  str->allocSize = num;
  return str->allocSize;
}
References infStr::allocSize, and infStr::str.
Referenced by append(), fillStr(), and initStr().
append()
infStr * append (infStr * str, char * chars, int num)
Append chars to the end of InfStr.
Parameters
str infStr object
chars new characters that need to be appended
num new character length
Todo
Todo clean and optimize allocation strategy
Definition at line 79 of file infStr.c.
                                                  {
  int alloc = 1;
  if(str->len + num >= str->allocSize) {
    
    alloc = str->allocSize;
    // allocate new memory
    while(alloc < num + str->len) {
      alloc = alloc * 2;
    }
    // simpan char lama, dealloc, balikin
    char* save = (char*) malloc(sizeof(char)*str->len+num+1);
    int old_len = str->len;
    strncpy(save, str->str, str->len);
    strncat(save, chars, num);
   
    free(str->str);
    allocStr(str, alloc);
    str->str = save;
    str->len = old_len + num;
    str->allocSize = alloc;
    str->start = str->str;
    str->end = str->str + str->len;
    return str;
    
  }
  // string aman
  strncat(str->str, chars, num);
  str->len = str->len + num;
  return str;
}
References infStr::allocSize, allocStr(), infStr::end, infStr::len, infStr::start, and infStr::str.
clear()
int clear (infStr * str)
Clear the string.
Returns
number of character that has been cleared
Parameters
str infStr object
Definition at line 117 of file infStr.c.
                       {
  str->str = str->start;
  
  str->end = str->start;
  return str->len;
}
References infStr::end, infStr::len, infStr::start, and infStr::str.
deallocStr()
void deallocStr (infStr * str)
deallocating memory should be called before lifetme of infStr end
Parameters
str InfStr object
Definition at line 142 of file infStr.c.
                             {
  str->end = str->start = 0;
  str->len = 0;
  free(str->str);
}
References infStr::end, infStr::len, infStr::start, and infStr::str.
fillStr()
int fillStr (infStr * str, char * chars, int num)
fill the string from the beginning.
Will fill the function from the beginning of the pointer Should be called when first time you want to fill in the function
Warning
Make sure the string is null terminated if the input string is literal string, make sure you append + 1 to include the null byte
Returns
initialized str object.
Parameters
str str object.
chars input characters
num length of chars
Definition at line 53 of file infStr.c.
                                               {
  if(num < 0) {
    fprintf(stderr, "string length cannot be negative");
    exit(-1);
  }
  int alloc = str->allocSize;
  while(alloc < num) {
    alloc = alloc * 2;
  }
  allocStr(str, alloc);
  char* ptr = chars;
  strncpy(str->str, chars, num);
  str->len = num;
  return num;
}
References infStr::allocSize, allocStr(), infStr::len, and infStr::str.
initStr()
infStr * initStr (infStr * str)
Initialize infStr.
This function should be called after infStr created.
Returns
initialized str object.
Parameters
str str object.
Definition at line 29 of file infStr.c.
                             {
  allocStr(str, 2);
  str->len = 0;
  str->start = str->str;
  str->end = str->str;
 return str;
}
References allocStr(), infStr::end, infStr::len, infStr::start, and infStr::str.